@baseUrl = http://localhost:3000
@visitsType=Амбулаторний

###

GET {{baseUrl}}/soldier
###

POST {{baseUrl}}/soldier
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
DELETE {{baseUrl}}/soldier/:id

###
GET {{baseUrl}}/visits/byType/{{visitsType}}

###
GET {{baseUrl}}/visits

###

POST {{baseUrl}}/visits
content-type: application/json

{
    "soldier": "6658514e75e5aaf0d261b668",
    "date_in": "Wed, 21 Oct 2015 18:27:50 GMT",
    "date_out": null,
    "pre_diagnosis": "травматолог",
    "final_diagnosis": "",
    "hospital_name": "",
    "type_of_visit": "Амбулаторний",
    "type_of_disease": "Хвороба",
    "complaint": "",
    "recomendation": "",
    "status": "Активний",
}