@baseURL = http://localhost:3000

###
GET {{baseURL}}/users

###
POST {{baseURL}}/auth
content-type: application/json

{
    "nickname": "admin",
    "password": "+"
}

###
GET  {{baseURL}}/structure
###
GET  {{baseURL}}/users

###
GET  {{baseURL}}/remission
###
POST {{baseURL}}/remission
content-type: application/json

{
    "soldier_id": "",
    "start_date": "2025-06-21T21:00:00.000Z",
    "end_date": "2025-06-25T21:00:00.000Z",
    "diagnosis": "pre",
    "description": "",
    "rank": "soldat",
    "name": "Yurii",
    "union": "mtz"
}
